# Generated by Django 2.0.5 on 2018-07-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvalidSMSContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contributor_id", models.CharField(max_length=100)),
                ("message_body", models.CharField(max_length=300)),
                ("date_received", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SMSContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contributor_id", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("water_height", models.FloatField()),
                ("temperature", models.FloatField(blank=True)),
                ("date_received", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("loc_latitude", models.FloatField()),
                ("loc_longitude", models.FloatField()),
                ("upper_bound", models.FloatField()),
                ("lower_bound", models.FloatField()),
                ("water_body_type", models.CharField(max_length=100)),
                (
                    "station_pic",
                    models.ImageField(blank=True, upload_to="station_pics"),
                ),
                ("status", models.BooleanField()),
                ("date_added", models.DateField()),
                ("sponsor_name", models.CharField(max_length=200)),
                (
                    "sponsor_pic",
                    models.ImageField(blank=True, upload_to="station_sponsor_pics"),
                ),
                ("sponsor_site", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="smscontribution",
            name="station_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.Station"
            ),
        ),
    ]
