# Generated by Django 2.0.5 on 2018-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="status",
            field=models.CharField(max_length=200),
        ),
    ]
