# Generated by Django 2.0.5 on 2018-07-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_auto_20180710_1434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidsmscontribution",
            name="contributor_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="invalidsmscontribution",
            name="date_received",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="smscontribution",
            name="contributor_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="smscontribution",
            name="date_received",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="smscontribution",
            name="state",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="smscontribution",
            name="station_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main_app.Station"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="loc_latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="station",
            name="loc_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="station",
            name="status",
            field=models.CharField(
                choices=[("OP", "Open"), ("IC", "In construction"), ("CD", "Closed")],
                default="OP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="water_body_type",
            field=models.CharField(
                choices=[
                    ("BR", "Brook"),
                    ("CA", "Cave"),
                    ("CR", "Creek"),
                    ("LA", "Lake"),
                    ("PO", "Pond"),
                    ("RI", "River"),
                ],
                default="RI",
                max_length=2,
            ),
        ),
    ]
