# Generated by Django 2.0.5 on 2018-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_auto_20180710_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="status",
            field=models.CharField(
                choices=[
                    ("OP", "Open"),
                    ("CS", "Coming Soon"),
                    ("UM", "Under Maintenance"),
                    ("CD", "Closed"),
                ],
                default="CS",
                max_length=2,
            ),
        ),
    ]
