# Generated by Django 2.0.5 on 2018-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_auto_20180711_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="sponsor_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
