# Generated by Django 2.0.5 on 2018-07-11 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_auto_20180711_1739"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsor",
            old_name="sponsor_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="sponsor",
            old_name="sponsor_pic",
            new_name="picture",
        ),
        migrations.RenameField(
            model_name="sponsor",
            old_name="sponsor_site",
            new_name="website",
        ),
    ]
