# Generated by Django 2.0.5 on 2018-07-11 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0009_auto_20180711_2011"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="sponsor",
            new_name="sponsor_1",
        ),
    ]
