# Generated by Django 2.0.5 on 2018-07-16 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0010_auto_20180711_2014"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smscontribution",
            old_name="station_id",
            new_name="station",
        ),
    ]
