# Generated by Django 2.0.5 on 2018-07-16 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0011_auto_20180716_1515"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smscontribution",
            name="state",
        ),
    ]
