# Generated by Django 2.0.5 on 2018-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0012_remove_smscontribution_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smscontribution",
            name="temperature",
            field=models.FloatField(blank=True, default=None),
        ),
    ]
