# Generated by Django 2.0.5 on 2018-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0013_auto_20180716_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smscontribution",
            name="temperature",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
