# Generated by Django 2.0.5 on 2019-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0015_auto_20190108_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smscontribution",
            name="water_height",
            field=models.FloatField(null=True),
        ),
    ]
