# Generated by Django 2.0.5 on 2019-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0016_auto_20190226_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidsmscontribution",
            name="date_received",
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name="smscontribution",
            name="date_received",
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="invalidsmscontribution",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="smscontribution",
            unique_together=set(),
        ),
    ]
