# Generated by Django 2.0.7 on 2019-03-21 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0017_auto_20190321_1348"),
        ("main_app", "0017_auto_20190226_1401"),
    ]

    operations = []
