# Generated by Django 2.1.5 on 2023-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0018_merge_20190321_1437"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyReceived",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_id", models.IntegerField()),
                ("contributor_id", models.UUIDField(null=True)),
                ("datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SurveySent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("survey_id", models.IntegerField()),
                ("contributor_id", models.UUIDField()),
                ("datetime", models.DateTimeField()),
            ],
        ),
    ]
