# Generated by Django 2.1.5 on 2023-01-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0019_surveyreceived_surveysent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyreceived",
            old_name="datetime",
            new_name="date_received",
        ),
        migrations.RenameField(
            model_name="surveysent",
            old_name="datetime",
            new_name="date_sent",
        ),
        migrations.RemoveField(
            model_name="surveyreceived",
            name="contributor_id",
        ),
        migrations.RemoveField(
            model_name="surveyreceived",
            name="survey_id",
        ),
        migrations.AddField(
            model_name="surveyreceived",
            name="response_id",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyreceived",
            name="survey_sent",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.SurveySent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveysent",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="surveysent",
            name="survey_id",
            field=models.CharField(max_length=20),
        ),
    ]
