# Generated by Django 2.1.5 on 2023-01-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0020_auto_20230120_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyreceived",
            name="response_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="surveyreceived",
            name="survey_sent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.SurveySent",
            ),
        ),
    ]
