# Generated by Django 2.1.5 on 2023-01-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0021_auto_20230120_1153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyreceived",
            name="survey_sent",
        ),
        migrations.AddField(
            model_name="surveyreceived",
            name="contributor_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyreceived",
            name="survey_id",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveysent",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
